spring:
  datasource:
    username: gsein
    password: bilibili
    url: jdbc:mysql://localhost:3306/platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60_000
      connect-timeout: 30_000
      test-while-idle: true
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          enabled: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 20230221001
  jpa:
    show-sql: true
logging:
  level:
    root: info
  file:
    name: logs/platform.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/platform-%d{yyyy-MM-dd}.%i.log
# 放行的url
security:
  ignore:
    urls:
      - /api/v1/user/login
      - /swagger-ui.html
      - /swagger-resources/**
      - /doc.html
      - /v2/api-docs
      - /webjars/**
      - /druid/**
      - /favicon.ico

